[project]
name = "tot_cmd"
version = "0.2.0"
description = "Default template for PDM package"
authors = [
    {name = "EstherCho-7", email = "dkgkqm777@gmail.com"},
]
dependencies = [
	'tot_plus>=0.1.1',
	'tot_minus>=0.1.3'
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = true
